version: "3.3"

services:
  postgres:
    image: postgres:latest
    container_name: my_store_db
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: my_store_pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin123
  #   ports:
  #     - "5050:80"
  mysql:
    image: mysql:latest
    container_name: my_store_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: my_store
      MYSQL_USER: root
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_data:/var/lib/mysql"
